apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundler
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymaster
spec:
  replicas: 1
