[profile.default]
src = "src"
test = "test"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
allow_paths = ["../hardhat", "../hardhat/node_modules"]
remappings = [
  "@openzeppelin/=../hardhat/node_modules/@openzeppelin/",
  "contracts/=../hardhat/contracts/"
]
