apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundler
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymaster
spec:
  replicas: 2
